<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RootNamespace>GE360.Trading.AlpacaPluginHost</RootNamespace>
    <AssemblyName>GE360.Trading.AlpacaPluginHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuantConnect.Brokerages.Alpaca" Version="2.5.17924" />
  </ItemGroup>
</Project>
